### ISSUE TITLE
Configuration not loaded/saved under Pale Moon

### ISSUE THREAD

**Issue by OmegaPhil** [sylecn/ff_nextpage#1]
Not sure if you are interested in supporting the [Pale Moon browser](https://www.palemoon.org/) (fork of Firefox), but reporting in case:

With Pale Moon 26.3.3 (and probably earlier versions), the addon installs but has no effect - looking at Preferences, there is no config file specified or built-in config, and while you can specify a user config and save/dismiss the form, bringing it back up again shows that the configuration hasn't been saved - nothing is there.

With Firefox, 'Config File' and 'Built-In Config' are populated.

**Comment by sylecn** [comment]
Thanks for the bug report.

This is because the Console.jsm js module has different path in firefox vs in palemoon.

It's fixed in nextpage v1.5.0. It will be uploaded on next nextpage update.

In the future, please report issues using the report-bug link in the add-on preferences or in the README file. For history reasons, the issues are not hosted in this project.
